# Configurações de Conexão com Banco de Dados
# Se estiver no Docker, ele usa as variáveis. Se não, usa o localhost padrão.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_projeto}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações Adicionais (Boas práticas para pools de conexão)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2 